name = "faux"
type = "webpack"
account_id = "{{CF_ACCOUNT_ID}}"
workers_dev = true
route = ""
zone_id = ""

[site]
bucket = "./out"
entry-point = "workers-site"

[env.production]
zone_id = "{{CF_ZONE_ID}}"
route = "faux.digital/*"