name: CI
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  push:
    branches:
      - master
jobs:
  vercel_deploy:
    name: Test setup
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to complete
        uses: patrickedqvist/wait-for-vercel-preview@master
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 120
  cypress:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          config: baseUrl=${{ needs.vercel_deploy.outputs.preview_url }}
          install: false # We test against live preview URL, no need to install packages
  lighthouse:
    name: Lighthouse audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        shell: bash -l {0}
        run: |
          nvm install
          nvm use
      - run: npm ci
      - run: npm run build:static
      - name: Run Lighthouse audit
        run: npx @lhci/cli@0.4.x autorun
        env:
          LHCI_BUILD_TOKEN: ${{ secrets.LHCI_BUILD_TOKEN }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
