name: CI
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  push:
    branches:
      - master
jobs:
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node install
        shell: bash -l {0}
        run: |
          nvm install
          nvm use
      - run: |
          npm ci
          npm run format:check
          npm run lint
          npx tsc --noEmit -p ./tsconfig.json
  vercel_deploy:
    name: Test setup
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to complete
        uses: patrickedqvist/wait-for-vercel-preview@master
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 120
  cypress:
    name: End-to-end tests
    needs: vercel_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          config: baseUrl=${{ needs.vercel_deploy.outputs.preview_url }}
          install: false # We test against a live preview URL, no need to install packages
  lighthouse:
    name: Lighthouse audit
    needs: vercel_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit Vercel preview URL using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ needs.vercel_deploy.outputs.preview_url }}
            ${{ needs.vercel_deploy.outputs.preview_url }}/blog
            ${{ needs.vercel_deploy.outputs.preview_url }}/login
            ${{ needs.vercel_deploy.outputs.preview_url }}/release-notes
            ${{ needs.vercel_deploy.outputs.preview_url }}/cards
          configPath: ./lighthouserc.js
          serverBaseUrl: ${{ secrets.LHCI_SERVER_BASE_URL }}
          serverToken: ${{ secrets.LHCI_BUILD_TOKEN }}
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  a11y:
    name: A11y audit
    needs: vercel_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a11y audit via Pa11y
        run: |
          sed -i 's|https://faux.digital|${{ needs.vercel_deploy.outputs.preview_url }}|g' .pa11yci.json
          npx pa11y-ci@2.x --config .pa11yci.json
