name: CI
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
env:
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
  NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY_API_KEY }}
  NEXT_PUBLIC_ALGOLIA_INDEX: ${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX }}
  NEXT_PUBLIC_GA_TRACKING_ID: ${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}
  NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
jobs:
  cypress:
    name: Integration
    runs-on: ubuntu-latest
    if: github.event == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node install
        shell: bash -l {0}
        run: nvm install
      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
          wait-on: http://localhost:3000
  lighthouse:
    name: Lighthouse audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        shell: bash -l {0}
        run: nvm install
      - run: npm install
      - run: npm run build:static
      - name: sanity
        with:
          entrypoint: /bin/echo
          args: ${{ github.event.pull_request.head.sha }}

      - name: Run Lighthouse audit
        run: npx @lhci/cli@0.4.x autorun
        env:
          LHCI_BUILD_TOKEN: ${{ secrets.LHCI_BUILD_TOKEN }}
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
