name: CI
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
jobs:
  static_analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node install
        shell: bash -l {0}
        run: |
          nvm install
          nvm use
      - run: |
          npm ci
          npm run format:check
          npm run lint
          npx tsc --noEmit -p ./tsconfig.json
